# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab9c85fb90efede9153e450eaa1ac8fc4c58ff586ef586df70a757e0d7c02281aa558ce374da6dff311386ebafdd4581b76b927357b18e4fee391b620e78d087

test:
  secret_key_base: 6f92c309f12d78c609f468d7f86c9125eb1d57378467ba3497a181e2388ee7a707a2d6e2d270b74c3687a2124bacdc2e18d0cd17c75df71291ba6fa042e483e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production_dev:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>